name: offthechain
description: A Markov Chain library.
version: 0.0.2
homepage: https://github.com/seanmccleary/offthechain
author: Sean McCleary <sean.mccleary@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  dddart:
    git: git@github.com:seanmccleary/dddart.git
  _discoveryapis_commons: any
  googleapis_auth: ^0.2.3+6
  logging: ^0.11.3+1

dev_dependencies:
  test: ^0.12.0
